import mongoose from "mongoose";
import Product from "./models/Product.js";
import dotenv from "dotenv";
dotenv.config();

const products = {
  vegetables: [
    {
      id: 1,
      name: "Organic Grapes",
      price: 4.99,
      originalPrice: 6.99,
      category: "vegetables",
      image: "🍇",
      rating: 4.5,
    },
    {
      id: 2,
      name: "Fresh Carrots",
      price: 1.49,
      originalPrice: 1.99,
      category: "vegetables",
      image: "🥕",
      rating: 4.2,
    },
    {
      id: 3,
      name: "Organic Tomatoes",
      price: 2.99,
      originalPrice: 3.49,
      category: "vegetables",
      image: "🍅",
      rating: 4.7,
    },
    {
      id: 4,
      name: "Cucumbers",
      price: 0.99,
      originalPrice: 1.29,
      category: "vegetables",
      image: "🥒",
      rating: 4.0,
    },
    {
      id: 5,
      name: "Bell Peppers",
      price: 1.79,
      originalPrice: 2.19,
      category: "vegetables",
      image: "🫑",
      rating: 4.3,
    },
    {
      id: 6,
      name: "Organic Apples",
      price: 3.49,
      originalPrice: 3.99,
      category: "vegetables",
      image: "🍏",
      rating: 4.8,
    },
  ],
  beverages: [
    {
      id: 7,
      name: "Mineral Water",
      price: 0.79,
      originalPrice: 0.99,
      category: "beverages",
      image: "💧",
      rating: 3.9,
    },
    {
      id: 8,
      name: "Orange Juice",
      price: 2.49,
      originalPrice: 2.99,
      category: "beverages",
      image: "🧃",
      rating: 4.5,
    },
    {
      id: 9,
      name: "Craft Beer",
      price: 3.99,
      originalPrice: 4.5,
      category: "beverages",
      image: "🍺",
      rating: 4.7,
    },
    {
      id: 10,
      name: "Green Tea",
      price: 3.29,
      originalPrice: 3.99,
      category: "beverages",
      image: "🍵",
      rating: 4.4,
    },
    {
      id: 11,
      name: "Cola Drink",
      price: 1.29,
      originalPrice: 1.5,
      category: "beverages",
      image: "🥤",
      rating: 4.1,
    },
    {
      id: 12,
      name: "Sparkling Water",
      price: 0.99,
      originalPrice: 1.2,
      category: "beverages",
      image: "🧊",
      rating: 4.0,
    },
  ],
  dairy: [
    {
      id: 13,
      name: "Milk 1L",
      price: 1.09,
      originalPrice: 1.29,
      category: "dairy",
      image: "🥛",
      rating: 4.2,
    },
    {
      id: 14,
      name: "Cheddar Cheese",
      price: 3.49,
      originalPrice: 3.99,
      category: "dairy",
      image: "🧀",
      rating: 4.6,
    },
    {
      id: 15,
      name: "Greek Yogurt",
      price: 2.19,
      originalPrice: 2.49,
      category: "dairy",
      image: "🍶",
      rating: 4.4,
    },
    {
      id: 16,
      name: "Butter 250g",
      price: 1.99,
      originalPrice: 2.29,
      category: "dairy",
      image: "🧈",
      rating: 4.3,
    },
    {
      id: 17,
      name: "Organic Eggs",
      price: 2.79,
      originalPrice: 3.19,
      category: "dairy",
      image: "🥚",
      rating: 4.7,
    },
    {
      id: 18,
      name: "Cream Cheese",
      price: 1.89,
      originalPrice: 2.1,
      category: "dairy",
      image: "🧀",
      rating: 4.5,
    },
  ],
  grains: [
    {
      id: 19,
      name: "Edible Oil Ghee",
      price: 45.0,
      originalPrice: 60.0,
      category: "grains",
      image: "🫒",
      rating: 4.8,
    },
    {
      id: 20,
      name: "Dry Fruits",
      price: 20.0,
      originalPrice: 22.0,
      category: "grains",
      image: "🥜",
      rating: 4.9,
    },
    {
      id: 21,
      name: "Whole Wheat Flour",
      price: 2.49,
      originalPrice: 2.99,
      category: "grains",
      image: "🌾",
      rating: 4.3,
    },
    {
      id: 22,
      name: "Basmati Rice",
      price: 4.99,
      originalPrice: 5.49,
      category: "grains",
      image: "🍚",
      rating: 4.7,
    },
    {
      id: 23,
      name: "Organic Quinoa",
      price: 5.99,
      originalPrice: 6.5,
      category: "grains",
      image: "🌾",
      rating: 4.6,
    },
    {
      id: 24,
      name: "Whole Grain Pasta",
      price: 2.19,
      originalPrice: 2.49,
      category: "grains",
      image: "🍝",
      rating: 4.4,
    },
  ],
  personal: [
    {
      id: 25,
      name: "Shampoo",
      price: 4.99,
      originalPrice: 5.99,
      category: "personal",
      image: "🧴",
      rating: 4.5,
    },
    {
      id: 26,
      name: "Toothpaste",
      price: 2.49,
      originalPrice: 2.99,
      category: "personal",
      image: "🪥",
      rating: 4.3,
    },
    {
      id: 27,
      name: "Hand Soap",
      price: 1.99,
      originalPrice: 2.29,
      category: "personal",
      image: "🧼",
      rating: 4.2,
    },
    {
      id: 28,
      name: "Face Cream",
      price: 8.99,
      originalPrice: 9.99,
      category: "personal",
      image: "🧴",
      rating: 4.7,
    },
    {
      id: 29,
      name: "Razor Blades",
      price: 5.49,
      originalPrice: 6.0,
      category: "personal",
      image: "🪒",
      rating: 4.4,
    },
    {
      id: 30,
      name: "Deodorant",
      price: 3.29,
      originalPrice: 3.79,
      category: "personal",
      image: "🧴",
      rating: 4.6,
    },
  ],
  pet: [
    {
      id: 31,
      name: "Dog Food",
      price: 12.99,
      originalPrice: 14.99,
      category: "pet",
      image: "🐕",
      rating: 4.8,
    },
    {
      id: 32,
      name: "Cat Litter",
      price: 8.49,
      originalPrice: 9.99,
      category: "pet",
      image: "🐈",
      rating: 4.5,
    },
    {
      id: 33,
      name: "Pet Toy",
      price: 5.99,
      originalPrice: 6.5,
      category: "pet",
      image: "🎾",
      rating: 4.7,
    },
    {
      id: 34,
      name: "Fish Food",
      price: 3.49,
      originalPrice: 3.99,
      category: "pet",
      image: "🐠",
      rating: 4.3,
    },
    {
      id: 35,
      name: "Bird Seed",
      price: 4.29,
      originalPrice: 4.99,
      category: "pet",
      image: "🦜",
      rating: 4.6,
    },
    {
      id: 36,
      name: "Pet Shampoo",
      price: 6.99,
      originalPrice: 7.5,
      category: "pet",
      image: "🛁",
      rating: 4.4,
    },
  ],
};

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    await Product.deleteMany();

    // Combine all products from all categories
    const allProducts = [
      ...products.vegetables,
      ...products.beverages,
      ...products.dairy,
      ...products.grains,
      ...products.personal,
      ...products.pet,
    ];

    await Product.insertMany(allProducts);
    console.log("Database seeded successfully!");
    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
}

seedDatabase();
